export const ExceptionType = {
  USERS_READ_NOT_FOUND: { id: 1, message: 'Users not found.' },
  USER_READ_NOT_FOUND: { id: 2, message: 'User by ID not found.' },
};

export const SuccessType = {
  USERS_SUCCESS: { id: 1, message: 'Users. Completed successfully.' },
};
